### ISSUE TITLE
Placement policies validation

### ISSUE THREAD

**Issue by EntropyEcosystem** [sonata-nfv/tng-policy-mngr#111]
Hi @efotopoulou the thing is that when I try to save (POST) a placement policy everything seems to be allowed but from the Portal I only know of three possible options: Load balanced, Prioritise and Fill first. Are there any other or can the user introduce whatever they want?

Then, when I try to save the policy "Prioritise", it is supposed to contain a list of ordered datacenters but I am not sure which key I must use for this. For example, I use { "policy": "the_policy" } but which is the key for this datacenter list?

Finally, when I GET the policy and the policy is "Prioritise" I should always get a list of datacenters ordered by priority.

**Comment by efotopoulou** [comment]
@anapolg i will proceed with the necessary placement policy validation next week and then ask confirmation from @tsoenen

**Comment by anapolg** [comment]
Do we have something new on this?

**Comment by efotopoulou** [comment]
sorry @anapolg ! i was fully dedicated until today with vnv issues. Hopefully from tomorrow i will be 100% at the sp and policy manager issues. 
i will keep you updated!

**Comment by efotopoulou** [comment]
@Ana just deployed a new version of policy manager where name of policies is validated. Only can be values of "Prioritise", "Load Balanced", "Fill First"

"datacenters" field is only stored for "Prioritise" type. for other types is ignored.

policy manager also checks if the datacenters uuid really exist by requesting the infrastracture manager.

some examples of post parameters are:
```
{
 "policy": "Prioritise",
 "datacenters": ["55da77d4-08dd-4ef1-9060-33d8a71cb87f","99c01993-bcde-4b87-8769-5bc2220bd438"]
}
```
OR
```
{
     "policy": "Fill First"
}
```
OR
```
{
     "policy": "Load Balanced"
}
```
Have in mind that now the existing placement policy is not shown at the portal. A GET call at http://pre-int-sp-ath.5gtango.eu:8081/api/v1/placement  returns the existing placement policy if any. 
Please re-open the issue if you think that is not properly addressed.

**Comment by anapolg** [comment]
Actually the GTK route is https://github.com/sonata-nfv/tng-api-gtw/blob/master/tng-router/config/sp_routes.yml#L108 but it does not work with a GET /policies/placement

Any idea?

**Comment by EntropyEcosystem** [comment]
i just did a PR. it should now work!
you should reach the latest placement policy here:
https://int-sp-ath.5gtango.eu/api/v3/policies/placement
